spring:
  application:
    name: auth-server
  redis:
    host: 139.198.30.134
    password: P@ssw0rd
    port: 30379
    timeout: 3000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gpi60l87gwnr2avms41d3kqoz9etcyub.mysql.qingcloud.link:3306/oauth2?useUnicode=true&usessl=false&characterEncoding=utf8
    username: paperless
    password: P@ssw0rdmysql
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        slf4j:
          enabled: true
        wall:
          enabled: true
        stat:
          enabled: true
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: admin


server:
  port: 8001

##服务器发现注册配置
#eureka:
#  client:
#    serviceUrl:
#      #配置服务中心(可配置多个,用逗号隔开)
#      defaultZone: http://admin:admin@localhost:9000/eureka/

##开启日志DEBUG级别，便于查看调试信息
logging.level.org.springframework.security: DEBUG

# mybatis-plus配置，不可修改
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: cn.poile.ucs.auth.entity
  global-config:
    db-config:
      # 配置逻辑删除，1：是，0：否
      logic-not-delete-value: 0
      logic-delete-value: 1
